site_name: HospitalRun
site_url: https://hospitalrun.io
site_description: HospitalRun project documentation
site_author: HospitalRun Core Team

repo_url: https://github.com/hospitalrun/hospitalrun/

nav:
  - Home: https://docs.hospitalrun.io
  - Devs Guide:
      - Frontend: https://docs.hospitalrun.io/projects/hospitalrun-frontend/en/latest/
      - Server: https://docs.hospitalrun.io/projects/hospitalrun-server/en/latest/
  - About:
      - Contributing: .github/CONTRIBUTING.md
      - License: LICENSE

theme:
  name: readthedocs
  highlightjs: true

extra_css:
  - css/style.css

plugins:
  - search
