site_name: HospitalRun
site_url: https://hospitalrun.io
site_description: HospitalRun project documentation
site_author: HospitalRun Core Team

repo_url: https://github.com/hospitalrun/hospitalrun/

nav:
  - Home: https://docs.hospitalrun.io
  - Users Guide: https://hospitalrun.io
  - Devs Guide:
      - Frontend: https://hospitalrun-frontend.readthedocs.io
      - Server: https://hospitalrun-server.readthedocs.io
  - About:
      - Project: https://hospitalrun.io
      - Contributing: https://github.com/HospitalRun/hospitalrun/blob/master/.github/CONTRIBUTING.md
      - License: https://github.com/HospitalRun/hospitalrun/blob/master/LICENSE

theme:
  name: readthedocs
  highlightjs: true

extra_css:
  - css/style.css

plugins:
  - search
