name: GitHub CI

on: [push, pull_request]

jobs:
  yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Clone submodules
        run: |
          git submodule update --init --recursive
      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install
      - name: Lint code
        run: |
          yarn workspaces run lint
      - name: Build
        run: |
          yarn workspaces run build
      - name: Run tests
        run: |
          npx cross-env CI=true yarn workspaces run test
